### ISSUE TITLE
Feature Request: Remove Hammers

### ISSUE THREAD

**Issue by K4N0** [jaredlll08/Fluxed-Crystals#1]
Suggestion: Remove the hammers and add a Crusher or such device. Making the blocks breakable with normal picks and get the drops would work as well but would be bad for automation.

**Comment by immibis** [comment]
Several different mods have block placers and breakers, so it wouldn't be _that_ bad. (MFR, SFM, TE, AE2, Botania, Buildcraft... even IC2, although it's not designed to be used that way so it's a huge pain)

**Comment by ghost** [comment]
In the new version of the mod hammers are removed.

https://github.com/jaredlll08/Fluxed-Crystals-Reborn

**Comment by immibis** [comment]
@JHarb52206 Rewriting the mod from scratch? Generally a bad idea...

**Comment by ghost** [comment]
Agreed. The new repo is not a full rewrite but enough change to warrent the move. Hopefully it will serve your needs.

**Comment by immibis** [comment]
@JHarb52207 Why a new repo then? I was currently fixing several things in the mod, but if they're already fixed, then that was a waste of effort... (Specifically: machines not running until a player opens their GUI, packet spamming to everyone in the dimension, and GUI energy bars)

**Comment by ghost** [comment]
You will need to talk to Jared about the move but yes all but the GUI bars have been fixed in the new version.

**Comment by ghost** [comment]
Curse has also been updated to point to the new repo as well.

**Comment by immibis** [comment]
@jaredlll08 why a new repo? Did you change the name of the mod? (in which case you could just rename the repo)

**Comment by ghost** [comment]
I will mention to him about putting some text on this one indicating the move as well. Not sure what the plan is for it.
