### ISSUE TITLE
Some bugs and suggestions

### ISSUE THREAD

**Issue by anishin** [jaredlll08/Fluxed-Crystals#11]
Firstly, thank you for creating this awesome mod!
I'm using version 0.0.4a. And I find some bugs:
1) When I break not mature crop, it doesn't drop seed.
2) When I break Powered Soil under the crop, it doesn't break.
3) I can place Rough Chunk in the same block, in which I'm standing (inside myself) and get x-ray glitch.
4) Rough Chunk name error ('tile.null.name' or 'Production Table', when Translocator is installed).
5) I can place more then one Rough Chunk into the same block (with Autonomous Activator from TE or Block Placer from OpenBlocks). And Autonomous Activator places Rough Chunk into TWO blocks:
![image](https://cloud.githubusercontent.com/assets/3234976/5701583/568903f2-9a5e-11e4-9ac2-97dd80c5300b.png)
And my suggestions for this cool mod:
1) Change material type of Powered Soil from rock to dirt.
2) Add more complex recipes for all machines from this mod. (Maybe, with EnderIO/TE/BloodMagic/Botania/ThaumCraft/IC2/GT? components). Now all recipes very cheap.
3) Add shift-clicking in all machines.
4) Add tooltips for all slots in machines.

Thank you for work!
P. S. Sorry for my English. I'm from Russia.

**Comment by jaredlll08** [comment]
Thanks ill look into them!

**Comment by jaredlll08** [comment]
All of the bugs have been fixed, thanks for giving me a heads up, the Autonomous activator will still fail to place my blocks correctly, this is a vanilla bug according to King lemming...
