### ISSUE TITLE
Can't create seeds in seed infuser

### ISSUE THREAD

**Issue by VivienV** [jaredlll08/Fluxed-Crystals#12]
After creating an Universal seed, I can't place the other material in the Seed Infuser. Tried with iron, gold, coal and a custom one I added to the JSON.

I'm on 0.0.4a, and this is the JSON file I changed (I only added a silicon seed at the end): http://pastebin.com/F7EtGr2C

The only other thing I changed was adding a new texture to shards (in my texture pack, not directly in the jar).

And, btw, thanks for this awesome mod. Can't wait to be able to use it as my main method of resource gathering.

**Comment by jaredlll08** [comment]
Can you give me some more information please, what slot were you trying to put the other materials in?

**Comment by VivienV** [comment]
The right one (it wouldn't accept it in either slot, though).

Not sure how helpful it is, but here's a screenshot: http://imgur.com/v8kfYUE

And modlist: http://pastebin.com/rKUDmuFW

The log messages say nothing. I'm unsure what other piece of information might help, but if you need anything just say it and I'll do my best to get it.

**Comment by jaredlll08** [comment]
Fixed it will roll out an update soon

**Comment by VivienV** [comment]
Thanks a lot! I will keep an eye out for a new version.
