### ISSUE TITLE
Farm manager causing crash to desktop upon placing the world

### ISSUE THREAD

**Issue by DBArcAngel** [jaredlll08/Fluxed-Crystals#13]
I will state that this crash happens with a mod pack and that i have informed the pack developers/maintainers of the issue first, I am posting the log here just incase it is something to do with this mod. It happens upon placing the farm manager not interacting with it(immediate crash upon placement). 

http://pastebin.com/LB7y2Xpc

I will close this post within the next few hours depending on what the response from the pack developers say/suggest.

**Comment by jaredlll08** [comment]
Without even looking im assuming the pack has IC2, It has been fixed(IC2 support is dropped btw))

**Comment by DBArcAngel** [comment]
Yes, my apologise for not mentioning that in the post

**Comment by jaredlll08** [comment]
Its fine :) the crash doesn't specifcly mention IC2 iirc
