### ISSUE TITLE
farm manager

### ISSUE THREAD

**Issue by fizzdizz** [jaredlll08/Fluxed-Crystals#14]
Pack: Material energy
Issue: farm manager +range upgrade
Description:  when a farm manager receives the range upgrade it causes massive lag.  I'm not sure if this is on your end or some random mod interaction but I wanted to report it.  I have to remove the item and break the block for it to return to normal.  

Caveat:  your mod is really cool man, keep up the great work!

**Comment by jaredlll08** [comment]
Fixed
