### ISSUE TITLE
r17 - Gem Refiner

### ISSUE THREAD

**Issue by Soulrift** [jaredlll08/Fluxed-Crystals#15]
Gem refiner is not functional in r17.  Tested both server and client setups.  Accepts RF and rough crystal, progress bar moves, but never outputs any smooth crystals.

Additionally, the "moving icon" graphic is glitchy, seems to flicker between two different textures

**Comment by jaredlll08** [comment]
Fixed, it is a feature :) meant to specify what it is changing into
