### ISSUE TITLE
Fluxed-Crystals UI Bug (Material Energy^4)

### ISSUE THREAD

**Issue by GIn-German** [jaredlll08/Fluxed-Crystals#19]
I still encounter a bug where the UI of all Machines except the Seed Infuser are corrupted and show a bizarre UI that cannot be fitted with anything. They accept power, but they never go beyond 250RF loaded within them and endlessly such out energy. The blocks are unable to work making the quests related to them impossible.

Attached are 4 pics showing the same UI for the Gem Cutter, Farm Manager and the other machine (forget the name). They were taken using the Material Energy^4 pack from the FTB launcher, ver. 1.0.3. . I spawned them via Creative Mode as quick test (crafting them yields the same result) and I even went so far to perform a full reset of the modpack without anything changing.

The mod itself was ver. 0.0.4.-b11 (0.0.4f) as read on the mod list page.

![2015-01-27_14 40 21](https://cloud.githubusercontent.com/assets/10725797/5919327/2bf9b290-a633-11e4-95e2-1a83427758ce.png)
![2015-01-27_14 40 30](https://cloud.githubusercontent.com/assets/10725797/5919329/2c0180f6-a633-11e4-9668-e02e6ecb6061.png)
![2015-01-27_14 40 33](https://cloud.githubusercontent.com/assets/10725797/5919331/2c032db6-a633-11e4-96c7-de9b913aa288.png)
![2015-01-27_14 40 35](https://cloud.githubusercontent.com/assets/10725797/5919330/2c016bfc-a633-11e4-8623-ad1d850d3e4b.png)
![2015-01-27_14 43 30](https://cloud.githubusercontent.com/assets/10725797/5919328/2c01741c-a633-11e4-8abf-3f82c4ab571a.png)

**Comment by jaredlll08** [comment]
talked this through
