### ISSUE TITLE
r21 - Replanting seed does not reset tick count

### ISSUE THREAD

**Issue by Soulrift** [jaredlll08/Fluxed-Crystals#24]
When you right click to harvest/auto-replant... the tick count doesn't appear to be resetting for the plant block.  Tested this with a Legendary Seed Bag from ME4, that has a 15 minute timer... after replanting, every time the block updated it progressed a new stage.

**Comment by Soulrift** [comment]
Issue lessened in r22/r23 - still needs to be investigated

**Comment by jaredlll08** [comment]
Fixed
