### ISSUE TITLE
Exceptions cought when the gem cutter is running

### ISSUE THREAD

**Issue by Cisien** [jaredlll08/Fluxed-Crystals#25]
http://paste.cisien.com/f/1fecfe7c.txt
The client also displays this message in the log:
[15:44:46] [Client thread/ERROR] [FML]: Detected ongoing potential memory leak. 200 packets have leaked. Top offenders 
[15:44:46] [Client thread/ERROR] [FML]: fluxedcrystals : 200

In the past this was caused by an incorrect implementation of netty.

**Comment by Soulrift** [comment]
What triggers this error? Using one of the machines? Or is it on load?

**Comment by Cisien** [comment]
As far as I have been able to tell this is on use and periodically after work Is done

**Comment by jaredlll08** [comment]
This has been fixed as far as I know.
