### ISSUE TITLE
Gem infuser

### ISSUE THREAD

**Issue by Aulton** [jaredlll08/Fluxed-Crystals#29]
In your most recent version displayed on Curse (0.0.4A) you cannot put items into the gem infuser to make the seed. Downgrading to the previous version fixed this, but I figured I would let you know.

**Comment by Soulrift** [comment]
This should be patched in the latest beta versions that we're working with.  You can get an updated stable build via Material Energy^4 1.0.4 off the FTB launcher.  We're hoping to have a new stable update on curseforge in the next couple days
