### ISSUE TITLE
Input Automation

### ISSUE THREAD

**Issue by blwilli12** [jaredlll08/Fluxed-Crystals#33]
both the Gem cuter and gem refiner will not input items correctly. I have tried Steve's factory manager, Ender IO, and even a vanilla hopper and it will not stop putting items in machine if the input slot is full it puts shards in the upgrade slot and the output slot. This was tested with the latest build of the mod 0.0.5 d

**Comment by ogredude** [comment]
Having the same issue, same build.  Ender IO conduit on top of gem cutter set to insert, and it will fill every single slot in the machine with items.  I haven't tested it with the gem refiner as I don't have enough smooth gems to give it a good run.
