### ISSUE TITLE
Breaking powered soil destroys the upgrades

### ISSUE THREAD

**Issue by mellamokb** [jaredlll08/Fluxed-Crystals#34]
When you break a powered soil block, the upgrades are lost.  They should be dropped separately or stored as part of the powered soil for next time you place it.  I did discover by accident that if you right-click on a powered soil block with an empty hand, it drops upgrades.

**Comment by jaredlll08** [comment]
Closed in https://github.com/jaredlll08/Fluxed-Crystals/commit/7c38e7d0a73fe43678222abd53cbf64dea977251
