### ISSUE TITLE
Right-clicking ItemDuct next to Powered Soil causes irrecoverable crash

### ISSUE THREAD

**Issue by mellamokb** [jaredlll08/Fluxed-Crystals#35]
I was trying to experiment with automation upgrades on Powered Soil.  It's not clear how it works, but I thought maybe using ItemDuct from EnderIO could retrieve the contents from the Powered Soil.  I placed itemducts and they connected to the powered soil, but when I right-click on the ItemDuct to access the configuration UI, my world crashed.  Now I am not able to login to the world either, it just crashes immediately.

Crash Log: http://pastebin.com/6KcLiqxL

This is on latest version [0.0.5d]

**Comment by blwilli12** [comment]
uses a vacuum chest to collect the shards/chunks from your crystal plants. this will get around the crash and to recover from the crash use mcedit to delete the power soil or the conduit to be able to get back in the world.

**Comment by mellamokb** [comment]
blwilli12: Yes, I figured out later that the items just drop and you can pick them up with a vacuum hopper.  I was able to fix my corrupt world with nbtexplorer by deleting the conduits.  Thanks!
