### ISSUE TITLE
Cannot cut rough crystals

### ISSUE THREAD

**Issue by RAnders00** [jaredlll08/Fluxed-Crystals#37]
http://youtu.be/VU76Ha4dxOk

**Comment by jaredlll08** [comment]
Sigh... Next time please make the video shorter... Pictures would suffice

You are inputting rough CHUNKS not rough SHARDS

**Comment by RAnders00** [comment]
The issue is that you are messing up the mcmod.info file and I had to proof that I was using the latest version. Make it better - the video can be shorter next time [update the version in build.gradle]

**Comment by jaredlll08** [comment]
place the rough chunks on the ground, break it with a crystal hammer, get rough shards from that, put rough shards in the gem cutter.
