### ISSUE TITLE
"Universal Seed" Seed impossible?

### ISSUE THREAD

**Issue by iarspider** [jaredlll08/Fluxed-Crystals#39]
I'm messing with ME^4 pack, and I've noticed that one can't create a "Universal Seed" seed. The config that is supposed to work:
```
	 {
            "name":"Universal Seed",
            "color":23658476,
            "ingredient":"fluxedcrystals:universalSeed;0",
            "dropMin":1,
            "dropMax":1,
            "growthTime":2400,
            "tier":1,
            "ingredientAmount":32,
            "powerPerStage":4000,
            "decorationBlocks":true,
            "weightedDrop":"fluxedcrystals:universalSeed;0",
            "weightedDropChance":1,
            "refinerAmount":16
        },
```

but the log shows this error:
```
[12:04:37] [Server thread/INFO] [FluxedCrystals/fluxedcrystals]: Skipping seed type with name Universal Seed as its drop was not found.
```

I'm using a version compiled from commit 45efd74d528b33fdb4400803baf708aa6d6f4413

**Comment by iarspider** [comment]
Still happens in 929139e3d3c755755afeddb9c083098bc3ee9257

**Comment by jaredlll08** [comment]
Did this work with the version included in the pack?

**Comment by iarspider** [comment]
This only happens on a Windows machine, with any version (0.0.4-b31 or compiled from source).

**Comment by jaredlll08** [comment]
that does not answer my question, does the universal seed appear with the version included in the pack

**Comment by iarspider** [comment]
This message happens with 0.0.4-b31 (version included in the pack). Crafting Universal Seed with this version is impossible: infuser yields Compressed Dirt seed. 

I have noticed something weird in the logs: http://pastebin.com/9HuPNxkt
The seeds are registered twice, and the second time all the seeds are registered without errors.
(the log is for 0.0.4-b31)

**Comment by iarspider** [comment]
With the latest revision, the seeds are registered three times...

**Comment by iarspider** [comment]
The seed is craftable, both on 0.0.4-b31 (version from the pack) and 0.0.5 custom-build, despite the log message. I have read the logs once more, and the seed registration code is ran twice (three times with version 929139e3d3c755755afeddb9c083098bc3ee9257), and it doesn't fail the 2nd (3rd time).

Issue is invalid, sorry!
