### ISSUE TITLE
Extracting from powered soil with enderio crashes server

### ISSUE THREAD

**Issue by krakentoa** [jaredlll08/Fluxed-Crystals#44]
Here's the crash log (was trying to avoid having more items dropping into my world by extracting chunks directly from powered soil):
http://pastebin.com/RQLB7Vze

**Comment by jaredlll08** [comment]
Did I not say that this was fixed? If not, it is fixed, the version isnt
released yet

**Comment by mellamokb** [comment]
krakentoa: I logged this issue already here: https://github.com/jaredlll08/Fluxed-Crystals/issues/35.

**Comment by jaredlll08** [comment]
Besides the fact that you CAN'T extract the chunks, this has been resolved.
