### ISSUE TITLE
Seeds incorrect if not running on Windows?

### ISSUE THREAD

**Issue by BenWoodford** [jaredlll08/Fluxed-Crystals#46]
There's been a lot of discussion surrounding this mod in ME^4, especially regarding the seeds being wrong outside Windows.

It would seem the ordering is off on both Linux and Mac, so most seeds show up as a different one to what they actually are. Replication environment for me is a Windows server with a Mac client connected.

The theory is the JSON files get read in a different order to Windows. But looking over how you read the config files that doesn't seem to be the case.

**Comment by amcoder** [comment]
I can confirm this happened to me as well in ME^4 on a Mac. Capitalizing the first letter of all of the json files fixed it for me, but it should probably be fixed so that files are read in the same order regardless of case.

**Comment by jaredlll08** [comment]
This was fixed in the latest version, so please can I have more info

**Comment by jaredlll08** [comment]
No reply after 4 days, closing
