### ISSUE TITLE
Disconnect (not crash) when opening Refinerey GUI

### ISSUE THREAD

**Issue by Skar78** [jaredlll08/Fluxed-Crystals#47]
Hi,

Everytime I put Smooth vibrant shards into a refinery the game disconnects (SP game).

If I reload and use a pickaxe to deconstruct the refinery i get usually only one vibrant ingot, despite maybe a whole stack of shards in the refinery. It doesnt matter how long i wait. It does not seem to work on the stack besides processing the first 4 shards into one ingot.

I tried this with and without torcherino time torch in that area, with and without speed upgrades.
However I did not try anything besides the smooth vibrant shard.

http://paste.atlauncher.com/view/51999cfb

**Comment by jaredlll08** [comment]
What version of Fluxed-Crystals are you using?

**Comment by Skar78** [comment]
0.0.5c as part of rr3.2.4

**Comment by jaredlll08** [comment]
Please try 0.0.5e

**Comment by Skar78** [comment]
issue not happening with 0.0.5e
