### ISSUE TITLE
Updating to 0.0.5e changed all seed types

### ISSUE THREAD

**Issue by thetaphi** [jaredlll08/Fluxed-Crystals#48]
I just tried to update to 0.0.5e after 0.0.5d crashed, and I wanted the fix to #35. Turns out that after the update, all planted seeds changed type. Triple compressed cookie went triple compressed theobromine, legendary reward bags went redstone...

The world is ME^4 with Fastcraft running.

Edit: Downgrading to 0.0.5d fixed my plantation, all seeds went back to normal.

**Comment by thetaphi** [comment]
OK, this has nothing to with the issue, but it's too good not to share.

For the record, the original crash was happening when I tried to harvest with Steve's Factory Manager block gates. So after the downgrade I needed another autoharvesting option. I decided to go for autonomous activators and vacuum hoppers, but then floating shards got stuck in the middle, where the hoppers negated each other. *Obvious* solution: Install fans.

As soon as I threw the lever to switch on the first fan, Minecraft crashed.

Blowing on planted seeds and floating shards with a fan crashes the game now? WHAT?!

Checking the crash log, it was the exact same AIOOB from before, with Ender IO clearly prominent in the stack trace. So I upgraded again, and had a closer look.
Turns out that directly above the lever was an item conduit going to a vacuum hopper, which after the downgrade was again connecting to a powered soil... in "Active with signal" mode...

**Comment by SirKastros** [comment]
the clay crystal seed is not working and throwing the items off so if you use 0.0.5f or newer remove the ID: line in the json file and they will create what they should. and also make sure to renumber all of the seeds or they will not create the right item 

12 -16 in the crystal json ( flint is 12 and skip the leather crystal entry)
17- 23 in the enderIO json
24-36 in the Thermal json
37+ in the custom json (for ME^4 is the the ME4 json)

**Comment by thetaphi** [comment]
I've beaten ME^4 since then, fair and square, so I doubt I'll test the procedure any time soon. I'll leave feedback if I do, but until then, /thread
