### ISSUE TITLE
fireworks go off from powered soil with seed on it.

### ISSUE THREAD

**Issue by SirKastros** [jaredlll08/Fluxed-Crystals#51]
I am using the latest build of the mod and fireworks start shooting off when there are seeds planted on the powered soil. When I take the seeds off they stop shooting.

**Comment by SirKastros** [comment]
![2015-04-02_19 29 21](https://cloud.githubusercontent.com/assets/6454124/6976376/96908372-d96e-11e4-97e1-726bad5dfaca.png)

**Comment by lanord** [comment]
Got the same thing with the latest version of mod on MA^4. What I can add to this bug report is that the firework goes off only when the seed progress and stop when at 100 % / is mature

**Comment by jaredlll08** [comment]
2 Words...
April Fools
