### ISSUE TITLE
seeds/shards mess uped.

### ISSUE THREAD

**Issue by killmetohell** [jaredlll08/Fluxed-Crystals#52]
some unknown reason one of my json file i have does not seem to detecting that it should the id have that after the 0.0.5g it has only one code that should put the item but i don't know why its not working.
![2015-04-12_02 10 59](https://cloud.githubusercontent.com/assets/11909414/7105028/4d40dd46-e0b9-11e4-9a13-f12a3cb4af5c.png)
![2015-04-12_02 11 03](https://cloud.githubusercontent.com/assets/11909414/7105027/4d407bd0-e0b9-11e4-9c30-54f0369dbe6d.png)

![customjusonfile](https://cloud.githubusercontent.com/assets/11909414/7105049/1c865ebe-e0ba-11e4-9356-76aca7630371.png)
![crystaljson](https://cloud.githubusercontent.com/assets/11909414/7105050/1c872ba0-e0ba-11e4-9b0b-bed7104631af.png)

can tell me whats wrong with if you can.

**Comment by jaredlll08** [comment]
In the latest version I removed the ID tag so just ignore it :)

**Comment by killmetohell** [comment]
ya i noticed on the updated wasn't sure what update meant
 is there any way to fix the mix up seeds.

**Comment by killmetohell** [comment]
i figured it out turns out it was adding a id for one of items that didn't notice it rearranged the seed positions. Can next update it would check if items has id then load item by order.

**Comment by jaredlll08** [comment]
No, that would be more of a mission than it is worth, sorry

**Comment by killmetohell** [comment]
oh ok can you at least how the load work from what figured it does by alphabetical order from json files but want sure if not there's more.

**Comment by jaredlll08** [comment]
Closing this because this issue has been resolved
