### ISSUE TITLE
world crash while configuring enderio stirling generator connected to powered soil

### ISSUE THREAD

**Issue by ArbitraryHubris** [jaredlll08/Fluxed-Crystals#53]
I am playing the pathfinder modpack (3rd party pack on ftb launcher) and have a stirling generator next to powered soil.  I tried to configure the face of the generator that is connected to the powered soil and it caused a crash.  Now I can't start that world.

http://pastebin.com/8fQKitvG (server crash)
http://pastebin.com/SgLM5tQX (client crash)

This is actually single player, not on a server.

I originally posted this issue on enderio github here: https://github.com/SleepyTrousers/EnderIO/issues/2333

**Comment by jaredlll08** [comment]
Replied on the EIO github, this is not my issue
